apiVersion: v1
kind: Service
metadata:
  labels:
    app: autoneg
    control-plane: controller-manager
  name: autoneg-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: autoneg
    control-plane: controller-manager